#!/bin/bash
#SBATCH -c 11
#SBATCH -n 1
#SBATCH --mem=80G
#SBATCH -p short
#SBATCH -t 8:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

# I made a caiman python environment activated in this way
source activate caiman

if [[ $# == 1 ]]; then
	python $HOME/code/caiman-pipeline/caiman-extract.py "$1"
else
	python $HOME/code/caiman-pipeline/caiman-extract.py
fi
