#!/bin/bash
#SBATCH -c 9
#SBATCH -n 1
#SBATCH --mem=90G
#SBATCH -p short
#SBATCH -t 3:15:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

# I made a caiman python environment activated in this way
source activate caiman

input_file="$1"
cnmf_options="$2"

if [[ $# -eq 3 ]]; then
	caiman-pipe extract ${input_file} ${cnmf_options} --n-procs 8 --out-file "$3"
else
	caiman-pipe extract ${input_file} ${cnmf_options} --n-procs 8
fi
