#!/bin/bash
#SBATCH -c 10
#SBATCH -n 1
#SBATCH --mem=60G
#SBATCH -p short
#SBATCH -t 5:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

source activate caiman

echo $1
caiman-pipe mc "$1" --rigid-splits 100
