#!/bin/bash
#SBATCH -c 9
#SBATCH -n 1
#SBATCH --mem=90G
#SBATCH -p short
#SBATCH -t 8:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

# I made a caiman python environment activated in this way
source activate caiman

caiman-pipe extract "$1" "$2" --n-procs 8
