#!/bin/bash
#SBATCH -c 2
#SBATCH -n 1
#SBATCH --mem=10G
#SBATCH -p short
#SBATCH -t 1:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

source activate caiman
if [ $# -lt 1 ]; then
	caiman-pipe concat-tiffs
else
	caiman-pipe concat-tiffs -i $1
fi


